name: Python package

on:
  push:
    branches: [ master, actions ]

  pull_request:
    branches: [ master, actions ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ 3.9, "3.10" ]
        django-version: [ 3.1, 3.2, 4.0 ]

    steps:
      - uses: actions/checkout@v2.3.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python dev.py -no-container
          pip install -q Django==${{ matrix.django-version }}
          python -m pip install --upgrade pip
          python setup.py install

      - name: Test with pytest
        run: |
          python runtests.py
